### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danieleguido** [C2DH/statec-exhibit#16]
- [x] Add missing legend cover homepage
- [x] Finalise dataset chapter 1
- [x] Add hotspots at chapter level
